// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efvroqtjfrwdsxzjzoob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdnJvcXRqZnJ3ZHN4emp6b29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDQ3ODUsImV4cCI6MjA3MzAyMDc4NX0.6ryuCQ8cAdNdnVHNeAR9P2q9olSmjDWXCvO0FgrH5Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});